// Authentication
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";

// PAGES
export const HOME_PAGE_REQUEST = "HOME_PAGE_REQUEST";
export const HOME_PAGE_SUCCESS = "HOME_PAGE_SUCCESS";
export const HOME_PAGE_FAILED = "HOME_PAGE_FAILED";

export const STORE_PAGE_REQUEST = "STORE_PAGE_REQUEST";
export const STORE_PAGE_SUCCESS = "STORE_PAGE_SUCCESS";
export const STORE_PAGE_FAILED = "STORE_PAGE_FAILED";

export const INVITE_CODE_STATE = "INVITE_CODE_STATE";

// Stores
export const GET_STORE_REQUEST = "GET_STORE_REQUEST";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const GET_STORE_FAILED = "GET_STORE_FAILED";

export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAILED = "CREATE_STORE_FAILED";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAILED = "UPDATE_STORE_FAILED";

export const UPDATE_STORE_PRODUCTS_REQUEST = "UPDATE_STORE_PRODUCTS_REQUEST";
export const UPDATE_STORE_PRODUCTS_SUCCESS = "UPDATE_STORE_PRODUCTS_SUCCESS";
export const UPDATE_STORE_PRODUCTS_FAILED = "UPDATE_STORE_PRODUCTS_FAILED";

export const ADD_POTENTIAL_STORE_REQUEST = "ADD_POTENTIAL_STORE_REQUEST";
export const ADD_POTENTIAL_STORE_SUCCESS = "ADD_POTENTIAL_STORE_SUCCESS";
export const ADD_POTENTIAL_STORE_FAILED = "ADD_POTENTIAL_STORE_FAILED";

export const SAVE_STORE_DATA_REQUEST = "SAVE_STORE_DATA_REQUEST";
export const SAVE_STORE_DATA_SUCCESS = "SAVE_STORE_DATA_SUCCESS";
export const SAVE_STORE_DATA_FAILED = "SAVE_STORE_DATA_FAILED";

// Users
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

export const ADD_INSTA_USERNAME_REQUEST = "ADD_INSTA_USERNAME_REQUEST";
export const ADD_INSTA_USERNAME_SUCCESS = "ADD_INSTA_USERNAME_SUCCESS";
export const ADD_INSTA_USERNAME_FAILED = "ADD_INSTA_USERNAME_FAILED";

export const GET_PERSONAL_DETAILS_REQUEST = "GET_PERSONAL_DETAILS_REQUEST";
export const GET_PERSONAL_DETAILS_SUCCESS = "GET_PERSONAL_DETAILS_SUCCESS";
export const GET_PERSONAL_DETAILS_FAILED = "GET_PERSONAL_DETAILS_FAILED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

// Addresses
export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED";

export const USER_ADDRESSES_REQUEST = "USER_ADDRESSES_REQUEST";
export const USER_ADDRESSES_SUCCESS = "USER_ADDRESSES_SUCCESS";
export const USER_ADDRESSES_FAILED = "USER_ADDRESSES_FAILED";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILED = "UPDATE_ADDRESS_FAILED";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILED = "DELETE_ADDRESS_FAILED";

// Orders
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export const VERIFY_ORDER_REQUEST = "VERIFY_ORDER_REQUEST";
export const VERIFY_ORDER_SUCCESS = "VERIFY_ORDER_SUCCESS";
export const VERIFY_ORDER_FAILED = "VERIFY_ORDER_FAILED";

export const PAST_ORDERS_REQUEST = "PAST_ORDERS_REQUEST";
export const PAST_ORDERS_SUCCESS = "PAST_ORDERS_SUCCESS";
export const PAST_ORDERS_FAILED = "PAST_ORDERS_FAILED";

export const CHECK_DELIVERY_REQUEST = "CHECK_DELIVERY_REQUEST";
export const CHECK_DELIVERY_SUCCESS = "CHECK_DELIVERY_SUCCESS";
export const CHECK_DELIVERY_FAILED = "CHECK_DELIVERY_FAILED";

// Invite Codes
export const ADD_INVITE_CODE_REQUEST = "ADD_INVITE_CODE_REQUEST";
export const ADD_INVITE_CODE_SUCCESS = "ADD_INVITE_CODE_SUCCESS";
export const ADD_INVITE_CODE_FAILED = "ADD_INVITE_CODE_FAILED";

// Products
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_FAILED = "SAVE_PRODUCT_FAILED";

export const GET_SAVED_PRODUCTS_REQUEST = "GET_SAVED_PRODUCTS_REQUEST";
export const GET_SAVED_PRODUCTS_SUCCESS = "GET_SAVED_PRODUCTS_SUCCESS";
export const GET_SAVED_PRODUCTS_FAILED = "GET_SAVED_PRODUCTS_FAILED";

export const DELETE_SAVED_PRODUCT_REQUEST = "DELETE_SAVED_PRODUCT_REQUEST";
export const DELETE_SAVED_PRODUCT_SUCCESS = "DELETE_SAVED_PRODUCT_SUCCESS";
export const DELETE_SAVED_PRODUCT_FAILED = "DELETE_SAVED_PRODUCT_FAILED";

// Search
export const SEARCH_STORES_REQUEST = "SEARCH_STORES_REQUEST";
export const SEARCH_STORES_SUCCESS = "SEARCH_STORES_SUCCESS";
export const SEARCH_STORES_FAILED = "SEARCH_STORES_FAILED";

export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS";
export const SEARCH_PRODUCTS_FAILED = "SEARCH_PRODUCTS_FAILED";

export const EXPLORE_PAGE_REQUEST = "EXPLORE_PAGE_REQUEST";
export const EXPLORE_PAGE_SUCCESS = "EXPLORE_PAGE_SUCCESS";
export const EXPLORE_PAGE_FAILED = "EXPLORE_PAGE_FAILED";

// Test
export const PING_SERVER_REQUEST = "PING_SERVER_REQUEST";
export const PING_SERVER_SUCCESS = "PING_SERVER_SUCCESS";
export const PING_SERVER_FAILED = "PING_SERVER_FAILED";

export const CHECK_LOGIN_REQUEST = "CHECK_LOGIN_REQUEST";
export const CHECK_LOGIN_SUCCESS = "CHECK_LOGIN_SUCCESS";
export const CHECK_LOGIN_FAILED = "CHECK_LOGIN_FAILED";
