import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bold Store</title>
        <meta name="description" content="Generated by Bold Store" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}> hi</div>
    </div>
  );
};

export default Home;
